import "dotenv/config";
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";
import express, { type Request, type Response } from "express";
import { VIDEOS_DIR } from "../cli/lib/paths.js";
import { loadDefaultConfig } from "../cli/lib/config.js";
import { inspectScript } from "../cli/commands/inspect.js";
import { InspectionFailedError, runPipeline, type PipelineEvent } from "../cli/commands/pipeline.js";

const PUBLIC_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "public");

interface Job {
  id: string;
  status: "running" | "done" | "error";
  events: PipelineEvent[];
  error?: string;
  clients: Response[];
}

const jobs = new Map<string, Job>();

function broadcast(job: Job, event: PipelineEvent | { type: "job-error"; message: string }) {
  const payload = `data: ${JSON.stringify(event)}\n\n`;
  for (const client of job.clients) {
    client.write(payload);
  }
}

function safeSlugPath(slug: string): string {
  // Slugs are generated by slugifyTheme() (lowercase, digits, hyphens only) — reject
  // anything else outright rather than trying to sanitize a path-traversal attempt.
  if (!/^[a-z0-9-]+$/.test(slug)) {
    throw new Error("Invalid slug");
  }
  const resolved = path.join(VIDEOS_DIR, slug);
  if (path.dirname(resolved) !== VIDEOS_DIR) {
    throw new Error("Invalid slug");
  }
  return resolved;
}

export async function startWebServer(port: number): Promise<void> {
  const app = express();
  app.use(express.json({ limit: "10mb" }));
  app.use(express.static(PUBLIC_DIR));

  app.post("/api/inspect", (req: Request, res: Response) => {
    const { text, targetDurationSeconds } = req.body ?? {};
    if (typeof text !== "string" || !text.trim()) {
      res.status(400).json({ error: "text is required" });
      return;
    }
    const config = loadDefaultConfig();
    const report = inspectScript({
      text,
      targetDurationSeconds: targetDurationSeconds ? Number(targetDurationSeconds) : undefined,
      config,
    });
    res.json(report);
  });

  app.post("/api/generate", (req: Request, res: Response) => {
    const {
      theme,
      targetDurationSeconds,
      format,
      musicPath,
      scriptText,
      skipInspection,
      manualMetadata,
    } = req.body ?? {};

    if (typeof theme !== "string" || !theme.trim()) {
      res.status(400).json({ error: "theme is required" });
      return;
    }
    const duration = Number(targetDurationSeconds) || 900;
    const formats: Array<"horizontal" | "vertical"> =
      format === "16x9" ? ["horizontal"] : format === "9x16" ? ["vertical"] : ["horizontal", "vertical"];

    const jobId = crypto.randomUUID();
    const job: Job = { id: jobId, status: "running", events: [], clients: [] };
    jobs.set(jobId, job);

    const onEvent = (event: PipelineEvent) => {
      job.events.push(event);
      broadcast(job, event);
    };

    runPipeline(
      {
        theme,
        targetDurationSeconds: duration,
        formats,
        musicPath: musicPath || undefined,
        scriptText: scriptText || undefined,
        skipInspection: Boolean(skipInspection),
        manualMetadata: manualMetadata || undefined,
      },
      onEvent
    )
      .then(() => {
        job.status = "done";
      })
      .catch((err) => {
        job.status = "error";
        job.error = err instanceof InspectionFailedError ? "Compliance check failed." : String(err?.message ?? err);
        broadcast(job, { type: "job-error", message: job.error });
      })
      .finally(() => {
        for (const client of job.clients) client.end();
        job.clients = [];
      });

    res.json({ jobId });
  });

  app.get("/api/jobs/:jobId/stream", (req: Request, res: Response) => {
    const job = jobs.get(req.params.jobId as string);
    if (!job) {
      res.status(404).end();
      return;
    }
    res.writeHead(200, {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache",
      Connection: "keep-alive",
    });
    // Replay buffered history first, so a page refresh mid-job doesn't miss anything.
    for (const event of job.events) {
      res.write(`data: ${JSON.stringify(event)}\n\n`);
    }
    if (job.status === "running") {
      job.clients.push(res);
      req.on("close", () => {
        job.clients = job.clients.filter((c) => c !== res);
      });
    } else {
      if (job.status === "error") {
        res.write(`data: ${JSON.stringify({ type: "job-error", message: job.error })}\n\n`);
      }
      res.end();
    }
  });

  app.get("/api/videos", (_req: Request, res: Response) => {
    if (!fs.existsSync(VIDEOS_DIR)) {
      res.json([]);
      return;
    }
    const results = [];
    for (const slug of fs.readdirSync(VIDEOS_DIR)) {
      const base = path.join(VIDEOS_DIR, slug);
      const outDir = path.join(base, "out");
      const configPath = path.join(base, "video.config.json");
      if (!fs.existsSync(outDir) || !fs.existsSync(configPath)) continue;
      const videoFiles = fs.readdirSync(outDir).filter((f) => f.endsWith(".mp4"));
      if (videoFiles.length === 0) continue;
      const metaFile = fs.readdirSync(outDir).find((f) => f.endsWith("_metadata.txt"));
      let theme = slug;
      let createdAt = "";
      try {
        const cfg = JSON.parse(fs.readFileSync(configPath, "utf-8"));
        theme = cfg.theme ?? slug;
        createdAt = cfg.createdAt ?? "";
      } catch {
        // fall back to slug
      }
      results.push({
        slug,
        theme,
        createdAt,
        videos: videoFiles.map((f) => ({ name: f, url: `/videos/${slug}/out/${f}` })),
        metadataUrl: metaFile ? `/videos/${slug}/out/${metaFile}` : null,
      });
    }
    results.sort((a, b) => (a.createdAt < b.createdAt ? 1 : -1));
    res.json(results);
  });

  app.get("/videos/:slug/out/:filename", (req: Request, res: Response) => {
    let outDir: string;
    try {
      outDir = path.join(safeSlugPath(req.params.slug as string), "out");
    } catch {
      res.status(400).end();
      return;
    }
    const filename = path.basename(req.params.filename as string);
    const filePath = path.join(outDir, filename);
    if (!filePath.startsWith(outDir) || !fs.existsSync(filePath)) {
      res.status(404).end();
      return;
    }
    res.sendFile(filePath);
  });

  await new Promise<void>((resolve) => {
    app.listen(port, () => {
      console.log(`\nMeditation pipeline web UI running at http://localhost:${port}\n`);
      resolve();
    });
  });
}
